ProningAnimation_From_Idle
lethalgem/music-shooter-game pull request #1
Opened 2024-02-08 01:32 UTC by ChapoTheGoat

This is way too ez - Proning animation from idle complete!

2024-02-08 01:38 UTC, lethalgem requested changes

2024-02-08 01:38 UTC, lethalgem commented on controllers/PronePlayerState.gd
> +	#elif Input.is_action_pressed("crouch") == false and RELEASED == false:  # When not holding crouch, set crouch_released to true. Then trigger unprone.
Please delete

2024-02-08 01:38 UTC, lethalgem commented on controllers/PronePlayerState.gd
> +		#unprone()
```suggestion
	#if CROUCH_SHAPECAST.is_colliding() == false and Input.is_action_pressed("crouch") == false:
		#ANIMATION.play("Crouching", -1.0, -PRONE_SPEED * 1.5, true)
		#if ANIMATION.is_playing():
			#await ANIMATION.animation_finished
		#transition.emit("IdlePlayerState")
	#elif CROUCH_SHAPECAST.is_colliding() == true:
		#await get_tree().create_timer(0.1).timeout
		#unprone()
```

2024-02-08 01:38 UTC, lethalgem commented on controllers/PronePlayerState.gd
> +	#elif Input.is_action_pressed("crouch") == false and RELEASED == false:  # When not holding crouch, set crouch_released to true. Then trigger unprone.
the comments not the code

2024-02-09 02:13 UTC, ChapoTheGoat commented on controllers/PronePlayerState.gd
> +	#elif Input.is_action_pressed("crouch") == false and RELEASED == false:  # When not holding crouch, set crouch_released to true. Then trigger unprone.
Too ez

2024-02-09 02:17 UTC, ChapoTheGoat commented on controllers/PronePlayerState.gd
> +		#unprone()
Way too ez

2024-02-09 02:17 UTC, lethalgem approved these changes

2024-02-09 02:18 UTC, lethalgem approved these changes

2024-02-09 02:20 UTC, ChapoTheGoat commented
Let me in!

2024-02-09 02:21 UTC, merged